//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEC.Nanoeye.NanoeyeSEM.Settings.MiniSEM {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class MicroscopeProfile : global::System.Configuration.ApplicationSettingsBase {
        
        private static MicroscopeProfile defaultInstance = ((MicroscopeProfile)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MicroscopeProfile())));
        
        public static MicroscopeProfile Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64")]
        public int Con1Default {
            get {
                return ((int)(this["Con1Default"]));
            }
            set {
                this["Con1Default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int Con1Maximum {
            get {
                return ((int)(this["Con1Maximum"]));
            }
            set {
                this["Con1Maximum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Con1Minimum {
            get {
                return ((int)(this["Con1Minimum"]));
            }
            set {
                this["Con1Minimum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64")]
        public int Con2Default {
            get {
                return ((int)(this["Con2Default"]));
            }
            set {
                this["Con2Default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Con1Invert {
            get {
                return ((bool)(this["Con1Invert"]));
            }
            set {
                this["Con1Invert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int Con2Maximum {
            get {
                return ((int)(this["Con2Maximum"]));
            }
            set {
                this["Con2Maximum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Con2Minimum {
            get {
                return ((int)(this["Con2Minimum"]));
            }
            set {
                this["Con2Minimum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Con2Invert {
            get {
                return ((bool)(this["Con2Invert"]));
            }
            set {
                this["Con2Invert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public int Obj1Default {
            get {
                return ((int)(this["Obj1Default"]));
            }
            set {
                this["Obj1Default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4095")]
        public int Obj1Maximum {
            get {
                return ((int)(this["Obj1Maximum"]));
            }
            set {
                this["Obj1Maximum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Obj1Minimum {
            get {
                return ((int)(this["Obj1Minimum"]));
            }
            set {
                this["Obj1Minimum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Obj1Invert {
            get {
                return ((bool)(this["Obj1Invert"]));
            }
            set {
                this["Obj1Invert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2048")]
        public int Obj2Default {
            get {
                return ((int)(this["Obj2Default"]));
            }
            set {
                this["Obj2Default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4095")]
        public int Obj2Maximum {
            get {
                return ((int)(this["Obj2Maximum"]));
            }
            set {
                this["Obj2Maximum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Obj2Minimum {
            get {
                return ((int)(this["Obj2Minimum"]));
            }
            set {
                this["Obj2Minimum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EgpsAccDefault {
            get {
                return ((int)(this["EgpsAccDefault"]));
            }
            set {
                this["EgpsAccDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EgpsTipDefault {
            get {
                return ((int)(this["EgpsTipDefault"]));
            }
            set {
                this["EgpsTipDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EgpsGridDefault {
            get {
                return ((int)(this["EgpsGridDefault"]));
            }
            set {
                this["EgpsGridDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EgpsEmitDefault {
            get {
                return ((int)(this["EgpsEmitDefault"]));
            }
            set {
                this["EgpsEmitDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EgpsPmtDefault {
            get {
                return ((int)(this["EgpsPmtDefault"]));
            }
            set {
                this["EgpsPmtDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EgpsCltDefault {
            get {
                return ((int)(this["EgpsCltDefault"]));
            }
            set {
                this["EgpsCltDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StigAlignXA {
            get {
                return ((int)(this["StigAlignXA"]));
            }
            set {
                this["StigAlignXA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StigAlignXB {
            get {
                return ((int)(this["StigAlignXB"]));
            }
            set {
                this["StigAlignXB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StigXDefault {
            get {
                return ((int)(this["StigXDefault"]));
            }
            set {
                this["StigXDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StigXWobEnable {
            get {
                return ((bool)(this["StigXWobEnable"]));
            }
            set {
                this["StigXWobEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StigXWobAmpl {
            get {
                return ((int)(this["StigXWobAmpl"]));
            }
            set {
                this["StigXWobAmpl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StigXWobFreq {
            get {
                return ((int)(this["StigXWobFreq"]));
            }
            set {
                this["StigXWobFreq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StigAlignYA {
            get {
                return ((int)(this["StigAlignYA"]));
            }
            set {
                this["StigAlignYA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StigAlignYB {
            get {
                return ((int)(this["StigAlignYB"]));
            }
            set {
                this["StigAlignYB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StigYDefault {
            get {
                return ((int)(this["StigYDefault"]));
            }
            set {
                this["StigYDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StigYWobEnable {
            get {
                return ((bool)(this["StigYWobEnable"]));
            }
            set {
                this["StigYWobEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StigYWobAmpl {
            get {
                return ((int)(this["StigYWobAmpl"]));
            }
            set {
                this["StigYWobAmpl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StigYWobFreq {
            get {
                return ((int)(this["StigYWobFreq"]));
            }
            set {
                this["StigYWobFreq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>20,	1.00000,	1.00000,	1</string>
  <string>30,	1.00000,	1.00000,	1</string>
  <string>50,	1.00000,	1.00000,	1</string>
  <string>75,	1.00000,	1.00000,	1</string>
  <string>100,	1.00000,	1.00000,	1</string>
  <string>150,	1.00000,	1.00000,	1</string>
  <string>200,	1.00000,	1.00000,	1</string>
  <string>300,	1.00000,	1.00000,	1</string>
  <string>500,	1.00000,	1.00000,	1</string>
  <string>750,	1.00000,	1.00000,	1</string>
  <string>1000,	1.00000,	1.00000,	1</string>
  <string>1500,	1.00000,	1.00000,	1</string>
  <string>2000,	1.00000,	1.00000,	1</string>
  <string>3000,	1.00000,	1.00000,	1</string>
  <string>5000,	1.00000,	1.00000,	0</string>
  <string>7500,	1.00000,	1.00000,	0</string>
  <string>10000,	1.00000,	1.00000,	0</string>
  <string>15000,	1.00000,	1.00000,	0</string>
  <string>20000,	1.00000,	1.00000,	0</string>
  <string>30000,	1.00000,	1.00000,	0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MagnificationSettings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MagnificationSettings"]));
            }
            set {
                this["MagnificationSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N.A.")]
        public string Alias {
            get {
                return ((string)(this["Alias"]));
            }
            set {
                this["Alias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float MagnificationWidth {
            get {
                return ((float)(this["MagnificationWidth"]));
            }
            set {
                this["MagnificationWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float MagnificationHeight {
            get {
                return ((float)(this["MagnificationHeight"]));
            }
            set {
                this["MagnificationHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ScanRotateOffset {
            get {
                return ((int)(this["ScanRotateOffset"]));
            }
            set {
                this["ScanRotateOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MagnificationFeedback {
            get {
                return ((int)(this["MagnificationFeedback"]));
            }
            set {
                this["MagnificationFeedback"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0kv")]
        public string EghvText {
            get {
                return ((string)(this["EghvText"]));
            }
            set {
                this["EghvText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SpotSize {
            get {
                return ((int)(this["SpotSize"]));
            }
            set {
                this["SpotSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WorkingDistance {
            get {
                return ((int)(this["WorkingDistance"]));
            }
            set {
                this["WorkingDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Amplifier {
            get {
                return ((int)(this["Amplifier"]));
            }
            set {
                this["Amplifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Collector {
            get {
                return ((int)(this["Collector"]));
            }
            set {
                this["Collector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StigX {
            get {
                return ((int)(this["StigX"]));
            }
            set {
                this["StigX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StigY {
            get {
                return ((int)(this["StigY"]));
            }
            set {
                this["StigY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GunAlignX {
            get {
                return ((int)(this["GunAlignX"]));
            }
            set {
                this["GunAlignX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GunAlignY {
            get {
                return ((int)(this["GunAlignY"]));
            }
            set {
                this["GunAlignY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BeamShiftX {
            get {
                return ((int)(this["BeamShiftX"]));
            }
            set {
                this["BeamShiftX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BeamShiftY {
            get {
                return ((int)(this["BeamShiftY"]));
            }
            set {
                this["BeamShiftY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Brightness {
            get {
                return ((int)(this["Brightness"]));
            }
            set {
                this["Brightness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Contrast {
            get {
                return ((int)(this["Contrast"]));
            }
            set {
                this["Contrast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int FilterCnt {
            get {
                return ((int)(this["FilterCnt"]));
            }
            set {
                this["FilterCnt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScanExternal {
            get {
                return ((bool)(this["ScanExternal"]));
            }
            set {
                this["ScanExternal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BeamShiftRotation {
            get {
                return ((int)(this["BeamShiftRotation"]));
            }
            set {
                this["BeamShiftRotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GunAlignRotation {
            get {
                return ((int)(this["GunAlignRotation"]));
            }
            set {
                this["GunAlignRotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EACL1 {
            get {
                return ((int)(this["EACL1"]));
            }
            set {
                this["EACL1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EACL2 {
            get {
                return ((int)(this["EACL2"]));
            }
            set {
                this["EACL2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EAAmplifier {
            get {
                return ((int)(this["EAAmplifier"]));
            }
            set {
                this["EAAmplifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EACollector {
            get {
                return ((int)(this["EACollector"]));
            }
            set {
                this["EACollector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int SS1CL1 {
            get {
                return ((int)(this["SS1CL1"]));
            }
            set {
                this["SS1CL1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int SS1CL2 {
            get {
                return ((int)(this["SS1CL2"]));
            }
            set {
                this["SS1CL2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int SS2CL1 {
            get {
                return ((int)(this["SS2CL1"]));
            }
            set {
                this["SS2CL1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int SS2CL2 {
            get {
                return ((int)(this["SS2CL2"]));
            }
            set {
                this["SS2CL2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int SS3CL1 {
            get {
                return ((int)(this["SS3CL1"]));
            }
            set {
                this["SS3CL1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int SS3CL2 {
            get {
                return ((int)(this["SS3CL2"]));
            }
            set {
                this["SS3CL2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EgpsGridRun {
            get {
                return ((int)(this["EgpsGridRun"]));
            }
            set {
                this["EgpsGridRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EgpsTipRun {
            get {
                return ((int)(this["EgpsTipRun"]));
            }
            set {
                this["EgpsTipRun"] = value;
            }
        }
    }
}
