//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEC.Nanoeye.NanoeyeSEM.Settings.MiniSEM {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class ScanningProfile : global::System.Configuration.ApplicationSettingsBase {
        
        private static ScanningProfile defaultInstance = ((ScanningProfile)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ScanningProfile())));
        
        public static ScanningProfile Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BlurLevel {
            get {
                return ((int)(this["BlurLevel"]));
            }
            set {
                this["BlurLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public float DeflectionMaximum {
            get {
                return ((float)(this["DeflectionMaximum"]));
            }
            set {
                this["DeflectionMaximum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-10")]
        public float DeflectionMinimum {
            get {
                return ((float)(this["DeflectionMinimum"]));
            }
            set {
                this["DeflectionMinimum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("320, 240")]
        public global::System.Drawing.Size FrameSize {
            get {
                return ((global::System.Drawing.Size)(this["FrameSize"]));
            }
            set {
                this["FrameSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 320, 240")]
        public global::System.Drawing.Rectangle ImageBounds {
            get {
                return ((global::System.Drawing.Rectangle)(this["ImageBounds"]));
            }
            set {
                this["ImageBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ImmediatePaint {
            get {
                return ((bool)(this["ImmediatePaint"]));
            }
            set {
                this["ImmediatePaint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MeanLevel {
            get {
                return ((int)(this["MeanLevel"]));
            }
            set {
                this["MeanLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 320, 240")]
        public global::System.Drawing.Rectangle PaintBounds {
            get {
                return ((global::System.Drawing.Rectangle)(this["PaintBounds"]));
            }
            set {
                this["PaintBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1250000")]
        public double SampleClock {
            get {
                return ((double)(this["SampleClock"]));
            }
            set {
                this["SampleClock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SampleComposite {
            get {
                return ((int)(this["SampleComposite"]));
            }
            set {
                this["SampleComposite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-16384, -16384, 32767, 32767")]
        public global::System.Drawing.Rectangle ScanningBounds {
            get {
                return ((global::System.Drawing.Rectangle)(this["ScanningBounds"]));
            }
            set {
                this["ScanningBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float TransformBarrel {
            get {
                return ((float)(this["TransformBarrel"]));
            }
            set {
                this["TransformBarrel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float TransformRotate {
            get {
                return ((float)(this["TransformRotate"]));
            }
            set {
                this["TransformRotate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float TransformShiftX {
            get {
                return ((float)(this["TransformShiftX"]));
            }
            set {
                this["TransformShiftX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float TransformShiftY {
            get {
                return ((float)(this["TransformShiftY"]));
            }
            set {
                this["TransformShiftY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VideoDifferential {
            get {
                return ((bool)(this["VideoDifferential"]));
            }
            set {
                this["VideoDifferential"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VideoChannel {
            get {
                return ((int)(this["VideoChannel"]));
            }
            set {
                this["VideoChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public float VideoMaximum {
            get {
                return ((float)(this["VideoMaximum"]));
            }
            set {
                this["VideoMaximum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-5")]
        public float VideoMinimum {
            get {
                return ((float)(this["VideoMinimum"]));
            }
            set {
                this["VideoMinimum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ScanState {
            get {
                return ((bool)(this["ScanState"]));
            }
            set {
                this["ScanState"] = value;
            }
        }
        
        /// <summary>
        /// ScanningBounds를 결정하는 수평 축척값입니다.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("ScanningBounds를 결정하는 수평 축척값입니다.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float ScanRatioX {
            get {
                return ((float)(this["ScanRatioX"]));
            }
            set {
                this["ScanRatioX"] = value;
            }
        }
        
        /// <summary>
        /// ScanningBounds를 결정하는 수직 축척값입니다.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("ScanningBounds를 결정하는 수직 축척값입니다.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.75")]
        public float ScanRatioY {
            get {
                return ((float)(this["ScanRatioY"]));
            }
            set {
                this["ScanRatioY"] = value;
            }
        }
        
        /// <summary>
        /// ScanningBounds를 결정하는 수평 이동값입니다.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("ScanningBounds를 결정하는 수평 이동값입니다.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float ScanShiftX {
            get {
                return ((float)(this["ScanShiftX"]));
            }
            set {
                this["ScanShiftX"] = value;
            }
        }
        
        /// <summary>
        /// ScanningBounds를 결정하는 수직 이동값입니다.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("ScanningBounds를 결정하는 수직 이동값입니다.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float ScanShiftY {
            get {
                return ((float)(this["ScanShiftY"]));
            }
            set {
                this["ScanShiftY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float TransformShearX {
            get {
                return ((float)(this["TransformShearX"]));
            }
            set {
                this["TransformShearX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float TransformShearY {
            get {
                return ((float)(this["TransformShearY"]));
            }
            set {
                this["TransformShearY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N.A.")]
        public string Alias {
            get {
                return ((string)(this["Alias"]));
            }
            set {
                this["Alias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PropargationDelayX {
            get {
                return ((double)(this["PropargationDelayX"]));
            }
            set {
                this["PropargationDelayX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PropargationDelayY {
            get {
                return ((double)(this["PropargationDelayY"]));
            }
            set {
                this["PropargationDelayY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AreaChangeSupport {
            get {
                return ((bool)(this["AreaChangeSupport"]));
            }
            set {
                this["AreaChangeSupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float AreaChangeX {
            get {
                return ((float)(this["AreaChangeX"]));
            }
            set {
                this["AreaChangeX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float AreaChangeY {
            get {
                return ((float)(this["AreaChangeY"]));
            }
            set {
                this["AreaChangeY"] = value;
            }
        }
    }
}
